In [19]:
import pandas as pd
import json
import requests

In [27]:
yelp_df = pd.read_excel("yelp_html.xlsx").head(10)
headers = {"Accept": "*/*", "Authorization": "Bearer "}

yelp_api_response=[]
for url in yelp_df['Business URL']:
    business_id = url.split('/')[-1]
    business_url= f"https://api.yelp.com/v3/businesses/{business_id}"

    r = requests.get(url=business_url, headers=headers)
    response_dict = json.loads(r.text)
    yelp_api_response.append(response_dict)
yelp_api_df = pd.DataFrame(yelp_api_response)
yelp_api_df.to_excel("yelp_response.xlsx")

In [43]:
google_csv_df = pd.read_excel('google_csv.xlsx').head(10)

google_csv_api_response=[]

for url in google_csv_df['URL']:
    url_string = 'https://maps.googleapis.com/maps/api/place/details/json?'
    cid = url.split(':')[-1]
    params = {'cid':cid, 'key':''}

    response = requests.get(url = url_string, params=params)
    response_dict = response.json()
    google_csv_api_response.append(response_dict)

normalize = [pd.json_normalize(item) for item in google_csv_api_response]

google_csv_api_df = pd.concat(normalize, ignore_index=True)
google_csv_api_df.to_excel("google_csv_response.xlsx")

Note: https://stackoverflow.com/questions/39011511/pandas-expand-rows-from-list-data-available-in-column

In [41]:
google_csv_api_df.explode('result.types')

,error_message,html_attributions,status,result.address_components,result.adr_address,result.business_status,result.current_opening_hours.open_now,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.delivery,...,result.user_ratings_total,result.utc_offset,result.vicinity,result.website,result.wheelchair_accessible_entrance,result.serves_breakfast,result.editorial_summary.language,result.editorial_summary.overview,result.curbside_pickup,result.serves_brunch
0,Invalid request. Invalid 'cid' parameter.,[],INVALID_REQUEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,[],OK,"[{'long_name': 'Suite 101', 'short_name': 'Sui...","<span class=""street-address"">2316 NE 65th St S...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: 11:00 AM...",True,...,214.0,-420.0,"2316 Northeast 65th Street Suite 101, Seattle",http://www.isarnkitchen.com/,True,NaN,NaN,NaN,NaN,NaN
1,NaN,[],OK,"[{'long_name': 'Suite 101', 'short_name': 'Sui...","<span class=""street-address"">2316 NE 65th St S...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: 11:00 AM...",True,...,214.0,-420.0,"2316 Northeast 65th Street Suite 101, Seattle",http://www.isarnkitchen.com/,True,NaN,NaN,NaN,NaN,NaN
1,NaN,[],OK,"[{'long_name': 'Suite 101', 'short_name': 'Sui...","<span class=""street-address"">2316 NE 65th St S...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: 11:00 AM...",True,...,214.0,-420.0,"2316 Northeast 65th Street Suite 101, Seattle",http://www.isarnkitchen.com/,True,NaN,NaN,NaN,NaN,NaN
1,NaN,[],OK,"[{'long_name': 'Suite 101', 'short_name': 'Sui...","<span class=""street-address"">2316 NE 65th St S...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: 11:00 AM...",True,...,214.0,-420.0,"2316 Northeast 65th Street Suite 101, Seattle",http://www.isarnkitchen.com/,True,NaN,NaN,NaN,NaN,NaN
2,NaN,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">6-chōme-5-1 Toyos...",OPERATIONAL,True,"[{'close': {'date': '2023-06-12', 'day': 1, 't...","[Monday: 6:00 AM – 2:00 PM, Tuesday: 6:00 AM –...",False,...,1326.0,540.0,"6-chōme-5-1 Toyosu, Koto City",https://twitter.com/sushidai_toyosu?ref_src=tw...,NaN,True,NaN,NaN,NaN,NaN
2,NaN,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">6-chōme-5-1 Toyos...",OPERATIONAL,True,"[{'close': {'date': '2023-06-12', 'day': 1, 't...","[Monday: 6:00 AM – 2:00 PM, Tuesday: 6:00 AM –...",False,...,1326.0,540.0,"6-chōme-5-1 Toyosu, Koto City",https://twitter.com/sushidai_toyosu?ref_src=tw...,NaN,True,NaN,NaN,NaN,NaN
2,NaN,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">6-chōme-5-1 Toyos...",OPERATIONAL,True,"[{'close': {'date': '2023-06-12', 'day': 1, 't...","[Monday: 6:00 AM – 2:00 PM, Tuesday: 6:00 AM –...",False,...,1326.0,540.0,"6-chōme-5-1 Toyosu, Koto City",https://twitter.com/sushidai_toyosu?ref_src=tw...,NaN,True,NaN,NaN,NaN,NaN
2,NaN,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">6-chōme-5-1 Toyos...",OPERATIONAL,True,"[{'close': {'date': '2023-06-12', 'day': 1, 't...","[Monday: 6:00 AM – 2:00 PM, Tuesday: 6:00 AM –...",False,...,1326.0,540.0,"6-chōme-5-1 Toyosu, Koto City",https://twitter.com/sushidai_toyosu?ref_src=tw...,NaN,True,NaN,NaN,NaN,NaN
3,NaN,[],OK,"[{'long_name': '5', 'short_name': '5', 'types'...","<span class=""street-address"">5 Wausan-ro 29ba-...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 11:00 AM – 10:00 PM,...",NaN,...,6.0,540.0,"5 Wausan-ro 29ba-gil, Seogyo-dong, Mapo-gu",https://www.instagram.com/kbottleshop/,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,[],OK,"[{'long_name': '5', 'short_name': '5', 'types'...","<span class=""street-address"">5 Wausan-ro 29ba-...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 11:00 AM – 10:00 PM,...",NaN,...,6.0,540.0,"5 Wausan-ro 29ba-gil, Seogyo-dong, Mapo-gu",https://www.instagram.com/kbottleshop/,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,[],OK,"[{'long_name': '5', 'short_name': '5', 'types'...","<span class=""street-address"">5 Wausan-ro 29ba-...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 11:00 AM – 10:00 PM,...",NaN,...,6.0,540.0,"5 Wausan-ro 29ba-gil, Seogyo-dong, Mapo-gu",https://www.instagram.com/kbottleshop/,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,[],OK,"[{'long_name': '5', 'short_name': '5', 'types'...","<span class=""street-address"">5 Wausan-ro 29ba-...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 11:00 AM – 10:00 PM,...",NaN,...,6.0,540.0,"5 Wausan-ro 29ba-gil, Seogyo-dong, Mapo-gu",https://www.instagram.com/kbottleshop/,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">Staroměstské nám....",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: 9:00 AM ...",NaN,...,52436.0,120.0,"Staroměstské náměstí 1, Praha 1",https://www.prague.eu/cs/objekt/mista/188/star...,True,NaN,en,Medieval timepiece on the facade of city hall ...,NaN,NaN
4,NaN,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">Staroměstské nám....",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: 9:00 AM ...",NaN,...,52436.0,120.0,"Staroměstské náměstí 1, Praha 1",https://www.prague.eu/cs/objekt/mista/188/star...,True,NaN,en,Medieval timepiece on the facade of city hall ...,NaN,NaN
4,NaN,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">Staroměstské nám....",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: 9:00 AM ...",NaN,...,52436.0,120.0,"Staroměstské náměstí 1, Praha 1",https://www.prague.eu/cs/objekt/mista/188/star...,True,NaN,en,Medieval timepiece on the facade of city hall ...,NaN,NaN
5,NaN,[],OK,"[{'long_name': '10A', 'short_name': '10A', 'ty...","<span class=""street-address"">Bayerstraße 10A</...",OPERATIONAL,NaN,NaN,NaN,NaN,...,3727.0,120.0,"Bayerstraße 10A, München",https://www.bahnhof.de/bahnhof-de/bahnhof/M-C3...,True,NaN,en,Airy mainline railway station with underground...,NaN,NaN
5,NaN,[],OK,"[{'long_name': '10A', 'short_name': '10A', 'ty...","<span class=""street-address"">Bayerstraße 10A</...",OPERATIONAL,NaN,NaN,NaN,NaN,...,3727.0,120.0,"Bayerstraße 10A, München",https://www.bahnhof.de/bahnhof-de/bahnhof/M-C3...,True,NaN,en,Airy mainline railway station with underground...,NaN,NaN
5,NaN,[],OK,"[{'long_name': '10A', 'short_name': '10A', 'ty...","<span class=""street-address"">Bayerstraße 10A</...",OPERATIONAL,NaN,NaN,NaN,NaN,...,3727.0,120.0,"Bayerstraße 10A, München",https://www.bahnhof.de/bahnhof-de/bahnhof/M-C3...,True,NaN,en,Airy mainline railway station with underground...,NaN,NaN
5,NaN,[],OK,"[{'long_name': '10A', 'short_name': '10A', 'ty...","<span class=""street-address"">Bayerstraße 10A</...",OPERATIONAL,NaN,NaN,NaN,NaN,...,3727.0,120.0,"Bayerstraße 10A, München",https://www.bahnhof.de/bahnhof-de/bahnhof/M-C3...,True,NaN,en,Airy mainline railway station with underground...,NaN,NaN
5,NaN,[],OK,"[{'long_name': '10A', 'short_name': '10A', 'ty...","<span class=""street-address"">Bayerstraße 10A</...",OPERATIONAL,NaN,NaN,NaN,NaN,...,3727.0,120.0,"Bayerstraße 10A, München",https://www.bahnhof.de/bahnhof-de/bahnhof/M-C3...,True,NaN,en,Airy mainline railway station with underground...,NaN,NaN
6,NaN,[],OK,"[{'long_name': '1911', 'short_name': '1911', '...","<span class=""street-address"">1911 N 45th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 3:00 – 9:00 PM, Wedn...",False,...,231.0,-420.0,"1911 North 45th Street, Seattle",http://indigocow.com/,True,NaN,NaN,NaN,False,NaN
6,NaN,[],OK,"[{'long_name': '1911', 'short_name': '1911', '...","<span class=""street-address"">1911 N 45th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 3:00 – 9:00 PM, Wedn...",False,...,231.0,-420.0,"1911 North 45th Street, Seattle",http://indigocow.com/,True,NaN,NaN,NaN,False,NaN
6,NaN,[],OK,"[{'long_name': '1911', 'short_name': '1911', '...","<span class=""street-address"">1911 N 45th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 3:00 – 9:00 PM, Wedn...",False,...,231.0,-420.0,"1911 North 45th Street, Seattle",http://indigocow.com/,True,NaN,NaN,NaN,False,NaN
6,NaN,[],OK,"[{'long_name': '1911', 'short_name': '1911', '...","<span class=""street-address"">1911 N 45th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 3:00 – 9:00 PM, Wedn...",False,...,231.0,-420.0,"1911 North 45th Street, Seattle",http://indigocow.com/,True,NaN,NaN,NaN,False,NaN
7,NaN,[],OK,"[{'long_name': '1519', 'short_name': '1519', '...","<span class=""street-address"">1519 14th Ave</sp...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 11:00 PM, Tuesday: 11:00 A...",True,...,1797.0,-420.0,"1519 14th Avenue, Seattle",http://www.nueseattle.com/,True,True,en,A memorabilia-packed dining room sets the tone...,True,True
7,NaN,[],OK,"[{'long_name': '1519', 'short_name': '1519', '...","<span class=""street-address"">1519 14th Ave</sp...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 11:00 PM, Tuesday: 11:00 A...",True,...,1797.0,-420.0,"1519 14th Avenue, Seattle",http://www.nueseattle.com/,True,True,en,A memorabilia-packed dining room sets the tone...,True,True
7,NaN,[],OK,"[{'long_name': '1519', 'short_name': '1519', '...","<span class=""street-address"">1519 14th Ave</sp...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 11:00 PM, Tuesday: 11:00 A...",True,...,1797.0,-420.0,"1519 14th Avenue, Seattle",http://www.nueseattle.com/,True,True,en,A memorabilia-packed dining room sets the tone...,True,True
7,NaN,[],OK,"[{'long_name': '1519', 'short_name': '1519', '...","<span class=""street-address"">1519 14th Ave</sp...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 11:00 PM, Tuesday: 11:00 A...",True,...,1797.0,-420.0,"1519 14th Avenue, Seattle",http://www.nueseattle.com/,True,True,en,A memorabilia-packed dining room sets the tone...,True,True
7,NaN,[],OK,"[{'long_name': '1519', 'short_name': '1519', '...","<span class=""street-address"">1519 14th Ave</sp...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 11:00 PM, Tuesday: 11:00 A...",True,...,1797.0,-420.0,"1519 14th Avenue, Seattle",http://www.nueseattle.com/,True,True,en,A memorabilia-packed dining room sets the tone...,True,True
8,NaN,[],OK,"[{'long_name': '2524', 'short_name': '2524', '...","<span class=""street-address"">2524 Beacon Ave S...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 4:30 – 10:30 PM, Wed...",NaN,...,412.0,-420.0,"2524 Beacon Avenue South, Seattle",https://www.musangseattle.com/,NaN,NaN,en,Contemporary space specializing in classic Fil...,False,True
8,NaN,[],OK,"[{'long_name': '2524', 'short_name': '2524', '...","<span class=""street-address"">2524 Beacon Ave S...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 4:30 – 10:30 PM, Wed...",NaN,...,412.0,-420.0,"2524 Beacon Avenue South, Seattle",https://www.musangseattle.com/,NaN,NaN,en,Contemporary space specializing in classic Fil...,False,True
8,NaN,[],OK,"[{'long_name': '2524', 'short_name': '2524', '...","<span class=""street-address"">2524 Beacon Ave S...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 4:30 – 10:30 PM, Wed...",NaN,...,412.0,-420.0,"2524 Beacon Avenue South, Seattle",https://www.musangseattle.com/,NaN,NaN,en,Contemporary space specializing in classic Fil...,False,True
8,NaN,[],OK,"[{'long_name': '2524', 'short_name': '2524', '...","<span class=""street-address"">2524 Beacon Ave S...",OPERATIONAL,True,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: Closed, Tuesday: 4:30 – 10:30 PM, Wed...",NaN,...,412.0,-420.0,"2524 Beacon Avenue South, Seattle",https://www.musangseattle.com/,NaN,NaN,en,Contemporary space specializing in classic Fil...,False,True
9,NaN,[],OK,"[{'long_name': '4804', 'short_name': '4804', '...","<span class=""street-address"">4804 SW 9th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: Closed, ...",True,...,420.0,-300.0,"4804 Southwest 9th Street, Des Moines",http://www.spicesofnepal.com/,True,NaN,NaN,NaN,NaN,False
9,NaN,[],OK,"[{'long_name': '4804', 'short_name': '4804', '...","<span class=""street-address"">4804 SW 9th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: Closed, ...",True,...,420.0,-300.0,"4804 Southwest 9th Street, Des Moines",http://www.spicesofnepal.com/,True,NaN,NaN,NaN,NaN,False
9,NaN,[],OK,"[{'long_name': '4804', 'short_name': '4804', '...","<span class=""street-address"">4804 SW 9th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: Closed, ...",True,...,420.0,-300.0,"4804 Southwest 9th Street, Des Moines",http://www.spicesofnepal.com/,True,NaN,NaN,NaN,NaN,False
9,NaN,[],OK,"[{'long_name': '4804', 'short_name': '4804', '...","<span class=""street-address"">4804 SW 9th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: Closed, ...",True,...,420.0,-300.0,"4804 Southwest 9th Street, Des Moines",http://www.spicesofnepal.com/,True,NaN,NaN,NaN,NaN,False
9,NaN,[],OK,"[{'long_name': '4804', 'short_name': '4804', '...","<span class=""street-address"">4804 SW 9th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: Closed, ...",True,...,420.0,-300.0,"4804 Southwest 9th Street, Des Moines",http://www.spicesofnepal.com/,True,NaN,NaN,NaN,NaN,False
9,NaN,[],OK,"[{'long_name': '4804', 'short_name': '4804', '...","<span class=""street-address"">4804 SW 9th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: Closed, ...",True,...,420.0,-300.0,"4804 Southwest 9th Street, Des Moines",http://www.spicesofnepal.com/,True,NaN,NaN,NaN,NaN,False
9,NaN,[],OK,"[{'long_name': '4804', 'short_name': '4804', '...","<span class=""street-address"">4804 SW 9th St</s...",OPERATIONAL,False,"[{'close': {'date': '2023-06-11', 'day': 0, 't...","[Monday: 11:00 AM – 9:00 PM, Tuesday: Closed, ...",True,...,420.0,-300.0,"4804 Southwest 9th Street, Des Moines",http://www.spicesofnepal.com/,True,NaN,NaN,NaN,NaN,False